<a href="https://colab.research.google.com/github/Abhishekpardhi46/Hello/blob/master/FDS%20Prac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(3,)


In [6]:
print(a[0],a[1],a[2])

1 2 3


In [9]:
b=np.array(([1,2],[3,4]))
b

array([[1, 2],
       [3, 4]])

In [11]:
print(b.shape)

(2, 2)
(2, 2)


In [12]:
print(b[0,0],b[0,1],b[1,1])

1 2 4


In [18]:
c=np.array([[1,2],[3,4],[5,6]])
print(c)
print(c[0,1],c[1,0],c[2,0],c[2,1])

[[1 2]
 [3 4]
 [5 6]]
2 3 5 6
